version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - apt-get install -y make
      # The Packer version in Bionic is extremely old (1.0), so install it manually
      - wget https://releases.hashicorp.com/packer/1.4.5/packer_1.4.5_linux_amd64.zip
      - echo "30da8dab9c526a6d15b037e2234f6f12cf3accfad77eb2c130738ec1a54cab6d  packer_1.4.5_linux_amd64.zip" | sha256sum -c
      - unzip packer_1.4.5_linux_amd64.zip
      - mv packer /usr/local/bin/packer
      - export AWS_DEFAULT_REGION=$AWS_REGION
  build:
    commands:
      # Build it in the current region instead of the hardcoded us-west-2
      - sed -ri "s/us-west-2/$AWS_REGION/g" eks-worker-al2.json
      - make 1.14
